package com.dorkag.azure_devops

import java.io.BufferedReader
import java.io.InputStreamReader


/*
* @author: jonathan.gafner
* @created: 19/12/2024
*/
@KoverAnnotation
class Anchor

fun getResourceAsText(path: String): String {
  val resourceStream = Anchor::class.java.getResourceAsStream(path)
  val jsonString = resourceStream?.let { BufferedReader(InputStreamReader(it)).readText() }
  return jsonString!!
}

/**
 * Removes metadata comments from generated YAML content.
 * Metadata comments are identified by lines starting with "# This file was generated by"
 * and subsequent metadata lines.
 */
fun stripMetadataComments(yamlContent: String): String {
  val lines = yamlContent.lines()
  val metadataEndIndex = lines.indexOfFirst { !it.startsWith("#") || it.isBlank() }
  return if (metadataEndIndex > 0) {
    lines.subList(metadataEndIndex, lines.size).joinToString("\n")
  } else {
    yamlContent
  }
}




