name: Gradle Plugin Portal Release

on:
  release:
    types: [ published ]  # triggers when you publish (not just create) a release

jobs:
  gradleRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          # If you want the commit on which the release was created:
          ref: ${{ github.event.release.tag_name }}

      # Set up Java environment if needed
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Provide environment variables for Gradle Publish Plugin
      - name: Publish to Gradle Plugin Portal
        run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          # If your plugin checks for these, they will be set

      # Optionally add steps to confirm success or upload logs